### ISSUE TITLE
Basilisk Issues/Todo (2017-02-04)

### ISSUE THREAD

**Issue by EvilJackCarver** [Pascal125/Faster-Than-Lizard-13#119]
Known issues as of #118:

* ~~Missing fire alarms:~~
  * ~~Gravgen~~
  * ~~R&D Server Room~~
  * Tcomms Server Room (intentional)
  * ~~Detective's Office~~
  * ~~Brig~~
* ~~Missing firelocks:~~
  * ~~R&D desk~~
  * ~~Munitions Office~~
* ~~Sec office fire alarm by armoury has too great a pixel_x (should be 24)~~
* Bushes by the window at the bar (admin spawn?)

Todo:
* ~~Remove a few more lights. Make lighting moodier.~~
  * Starboard hall/locker room is the degree of moodiness I'm looking for.
  * Captain's quarters and HoP's office, could probably get away with just two small fixtures (cap's bed can use one)
  * AI quarters could replace the tubes with bulbs
  * Could move pub's lighting to where the sec camera is
  * ***Do not adjust lighting in evac shuttle***
* ~~Delete all the status displays, and rework them from square one~~
* ~~Add exit button to medbay doors~~
  * Have both sets on separate channels
* ~~Add signs pointing to evac, engi, sci, sec, etc~~
* Add intercoms/extinguishers

**Comment by SgtxRootbeer** [comment]
I will look into this, when I return home.

**Comment by Pascal125** [comment]
Optionally you could look into adding Intercomms / Extinguisher closets around the shuttle...

I believe the "Bush" outside the bar is from when they landed on a planet. Some objects and such do not seem to despawn, though i'm not sure why.
