### ISSUE TITLE
badmin/trialmin updating.

### ISSUE THREAD

**Issue by SgtxRootbeer** [Pascal125/Faster-Than-Lizard-13#151]
**Problem Description**:
hits is trialmin

**What did you expect to happen**: 
hits to be badmin, or at least gameadmin

**What happened instead**:
hits lost some admin commands

**Why is this bad/What are the consequences:**
hits cant do as much fun stuff

**Steps to reproduce the problem**:
log in
wait for hits to long in (skip if he's already logged in)
press adminwho
notice trialmin status

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
you gave me gameadmin once, but then i lost it pending the end of that round/compiling of the server.

**Comment by SgtxRootbeer** [comment]
if anyone has any more lables that this might need, please, dont hesitate to let me know.

**Comment by SgtxRootbeer** [comment]
whoops, forgot those. very important

**Comment by EvilJackCarver** [comment]
Let's not abuse the labels. It makes it very difficult to search through issues if we have to revert to a known good version.

**Comment by SgtxRootbeer** [comment]
you are like... no fun.

**Comment by SgtxRootbeer** [comment]
I need to make a new issue on GitHub now, as it only e-mailed me about this 1.5 hrs after you closed it.
