### ISSUE TITLE
HOLODEK IS BROKEN 

### ISSUE THREAD

**Issue by SgtxRootbeer** [Pascal125/Faster-Than-Lizard-13#41]
the room "holodec rec" isnt recognized as part of the ship, and, during translation, it is left behind.
good news, the hole does not extend to the hallway, and instead, is behind the airlocks that normally guard the holodek.
PASCAL, its your turn to do something

**Comment by SgtxRootbeer** [comment]
oi, i see that map tag, i bet this is your attempts to blame it on my shoddy, broken, filled with errors mapping.
the best part, you're prolly right!

**Comment by Pascal125** [comment]
Fixed. https://github.com/Pascal125/Faster-Than-Lizard-13/pull/46
